Repository APKLab/APKLab, pull requests merged in 2021-01, with the labels that each got.

#78 lint: adapt eslint-plugin-import rules
  .eslintrc.json
  package-lock.json
  package.json
  src/common.ts
  src/downloader.ts
  src/mitm-tools.ts
  src/test/runTest.ts
  src/test/suite/extension.test.ts
  src/tools.ts
Labels: lint

#77 build: clean workspace before packaging
  .vscode/launch.json
  package.json
Labels: build

#76 dep: use `execa` instead of `child_process`
  package-lock.json
  package.json
Labels: dependencies

#80 misc: add `samlise` as extension dependency
  README.md
  package-lock.json
  package.json
Labels: new-tool

#91 Improve VS Code configs
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: enhancement

#74 test: enable tests for more testable features
  .vscode/launch.json
  src/test/suite/extension.test.ts
Labels: test

#83 CI: update ubuntu image to ubuntu-20.04
  .github/workflows/apklab.yml
Labels: CI, build, test
